version: '3.8'

services:
  pg_master:
    image: postgres:latest
    container_name: pg_master
    restart: unless-stopped
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - pg_net
    volumes:
      - ./volumes/pg_master:/var/lib/postgresql/data
      - ./volumes/pg_slave:/pg_slave
      - ./volumes/pg_asyncslave:/pg_asyncslave

networks:
  pg_net:
    external: true
