version: '3.8'

services:
  springbootapp:
    build:
      context: ./src
    container_name: springbootapp
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/user
      DATABASE_USER: postgres
      DATABASE_PASSWORD: pass
    depends_on:
      - db
      - pgasyncslave
      - pgslave
    ports:
      - "8081:8080"
    networks:
      - highloadnet

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - highloadnet

  pgasyncslave:
    image: postgres:latest
    container_name: pgasyncslave
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pgasyncslave-data:/var/lib/postgresql/data
    networks:
      - highloadnet

  pgslave:
    image: postgres:latest
    container_name: pgslave
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pgslave-data:/var/lib/postgresql/data
    networks:
      - highloadnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - highloadnet

volumes:
  db-data:
  pgasyncslave-data:
  pgslave-data:
  pgadmin-data:

networks:
  highloadnet:
    driver: bridge
