services:
  ansible:
    build:
      context: ./ansible
      dockerfile: Dockerfile
    container_name: ansible
    restart: unless-stopped
    networks:
      - pg_net
    volumes:
      - ./ansible/playbooks/:/ansible/playbooks
      - /var/run/docker.sock:/var/run/docker.sock

  pg_master:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: db:local
    container_name: pg_master
    restart: unless-stopped
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "35432:5432"
    networks:
      - pg_net
    volumes:
      - pg_master:/var/lib/postgresql/data

  pg_slave:
    image: db:local
    depends_on:
      - pg_master
    container_name: pg_slave
    restart: unless-stopped
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "35434:5432"
    networks:
      - pg_net
    volumes:
      - pg_slave:/var/lib/postgresql/data

  pg_asyncslave:
    image: db:local
    depends_on:
      - pg_master
    container_name: pg_asyncslave
    restart: unless-stopped
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "35436:5432"
    networks:
      - pg_net
    volumes:
      - pg_asyncslave:/var/lib/postgresql/data

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - pg_net

  app:
    build:
      context: ./app
    container_name: app
    restart: unless-stopped
    depends_on:
      - pg_master
      - pg_slave
      - pg_asyncslave
    networks:
      - pg_net
    ports:
      - "8080:8080"

  # pgadmin:
    # image: dpage/pgadmin4:latest
    # container_name: pgadmin
    # restart: unless-stopped
    # environment:
      # PGADMIN_DEFAULT_EMAIL: admin@admin.com
      # PGADMIN_DEFAULT_PASSWORD: admin
    # ports:
      # - "5050:80"
    # volumes:
      # - pgadmin_data:/var/lib/pgadmin
    # networks:
      # - pg_net

volumes:
  pg_master:
  pg_slave:
  pg_asyncslave:
  pgadmin_data:

networks:
  pg_net:
    external: true
