FROM python:latest
RUN apt-get update && \
    apt-get install -y --no-install-recommends bash && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /
COPY pg_backup/pg_backup.part.* /tmp/
RUN cat /tmp/pg_backup.part.* > /pg_backup.tar
COPY setup.py /setup.py
RUN chmod +x /setup.py
USER root
ENTRYPOINT ["python", "/setup.py"]
