---
- name: Включить репликацию. pg_master - primary
  hosts: pg_servers
  become: true
  gather_facts: false

  vars:
    pg_admin_user: postgres
    pg_admin_password: postgres
    pg_db_name: user
    pg_hba_conf_path: /var/lib/postgresql/data/pg_hba.conf
    db_image: '--filter ancestor=db:local'
    
  tasks: 
    - name: Установить ssl=off
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: ssl
        value: off

    - name: Установить wal_level=replica
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: wal_level
        value: replica

    - name: Установить max_wal_senders=20
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: max_wal_senders
        value: 20

    - name: Получить подсеть pg_net
      command: docker network inspect pg_net
      register: network_info_raw
      delegate_to: localhost

    - name: Дать пользователю replicator доступ к сети в pg_hba.conf
      postgresql_pg_hba:
        dest: /var/lib/postgresql/data/pg_hba.conf
        contype: host
        users: replicator
        source: "{{ (network_info_raw.stdout | from_json)[0].IPAM.Config[0].Subnet }}"
        databases: replication
        method: md5
 
    - name: Создать standby.signal
      file:
        path: /var/lib/postgresql/data/standby.signal
        state: touch
        owner: postgres
        group: postgres
        mode: '0644'
      when: "'pg_master' not in inventory_hostname"  
      
    - name: Установить conninfo pg_slave
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: primary_conninfo
        value: "host=pg_master port=5432 user=replicator password=pass application_name=pg_slave"
      when: "'pg_slave' in inventory_hostname"  
      
    - name: Установить conninfo pg_asyncslave
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: primary_conninfo
        value: "host=pg_master port=5432 user=replicator password=pass application_name=pg_asyncslave"
      when: "'pg_asyncslave' in inventory_hostname"  
      
    - name: Установить synchronous_commit на pg_master
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: synchronous_commit
        value: "on"
      when: "'pg_master' in inventory_hostname"  
 
    - name: Установить synchronous_standby_names ANY на pg_master
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: synchronous_standby_names
        value: "ANY 1 (pg_slave, pg_asyncslave)"
      when: "'pg_master' in inventory_hostname"   
 
    - name: Получить имена контейнеров для перезагрузки
      command: docker container ls -a {{ db_image }} --format "{{ '{{' }}.Names {{ '}}' }} {{ '{{' }}.Image {{ '}}' }}"
      register: docker_images
      run_once: true
      delegate_to: localhost

    - name: Перезагрузка
      docker_container:
        name: "{{ item.split(' ')[0]}}"
        image: "{{ item.split(' ')[1]}}"
        state: started
        restart: yes
      loop: "{{ docker_images.stdout_lines}}"
      run_once: true
      delegate_to: localhost
      
    - name: Проверить pg_stat_replication
      community.postgresql.postgresql_query:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        query: "select application_name, sync_state from pg_stat_replication;"
      register: replication_status
      until: replication_status.query_result | length > 0
      retries: 30
      delay: 10
      when: "'pg_master' in inventory_hostname"

    - name: Вывести pg_stat_replication
      debug:
        msg:
          - "{{ replication_status.query_result }}"
      when: "'pg_master' in inventory_hostname"