---
- name: Отключить pg_master. Сделать pg_slave primary. Перенастроить pg_asyncslave на новый primary.
  hosts: highload_servers
  become: true
  gather_facts: false

  vars:
    pg_admin_user: postgres
    pg_admin_password: postgres
    pg_db_name: user
    pg_hba_conf_path: /var/lib/postgresql/data/pg_hba.conf
    image_filters: '--filter ancestor=db:local --filter ancestor=app:local'
    application_properties_content: |
      spring.application.name=Highload Architect

      spring.datasource.url=jdbc:postgresql://pg_slave:5432/user
      spring.datasource.username=postgres
      spring.datasource.password=postgres
      spring.datasource.driver-class-name=org.postgresql.Driver

      spring.datasource.secondary.url=jdbc:postgresql://pg_slave:5432/user
      spring.datasource.secondary.username=postgres
      spring.datasource.secondary.password=postgres
      spring.datasource.secondary.driver-class-name=org.postgresql.Driver

      spring.datasource.tertiary.url=jdbc:postgresql://pg_slave:5432/user
      spring.datasource.tertiary.username=postgres
      spring.datasource.tertiary.password=postgres
      spring.datasource.tertiary.driver-class-name=org.postgresql.Driver

  tasks:
    - name: Посчитать количество записей в user_account
      postgresql_query:
        db: "{{ pg_db_name }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        query: "SELECT COUNT(*) FROM user_account;"
      register: count_users_before
      when: inventory_hostname in ['pg_master', 'pg_slave', 'pg_asyncslave']

    - name: Вывести количество записей в user_account
      debug:
        msg: "{{ count_users_before.query_result }} записей"
      when: inventory_hostname in ['pg_master', 'pg_slave', 'pg_asyncslave']

    - name: Включить нагрузку на запись в pg_master
      pause:
        seconds: 120
      run_once: true

    - name: Остановить pg_asyncslave
      docker_container:
        name: "pg_asyncslave"
        image: "db:local"
        state: stopped
      run_once: true
      delegate_to: localhost

    - name: Выключить нагрузку на запись в pg_master
      pause:
        seconds: 120
      run_once: true
      
    - name: Остановить мастер
      docker_container:
        name: "pg_master"
        image: "db:local"
        state: stopped
      run_once: true
      delegate_to: localhost
      
    - name: Запустить pg_asyncslave
      docker_container:
        name: "pg_asyncslave"
        image: "db:local"
        state: started
      run_once: true
      delegate_to: localhost

    - name: Посчитать количество записей в user_account
      postgresql_query:
        db: "{{ pg_db_name }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        query: "SELECT COUNT(*) FROM user_account;"
      register: count_users_after
      when: inventory_hostname in ['pg_slave', 'pg_asyncslave']

    - name: Вывести количество записей в user_account
      debug:
        msg: "{{ count_users_after.query_result }} записей"
      when: inventory_hostname in ['pg_slave', 'pg_asyncslave']

    - name: Запустить мастер
      docker_container:
        name: "pg_master"
        image: "db:local"
        state: started
      run_once: true
      delegate_to: localhost

    - name: Настроить application.properties
      copy:
        content: "{{ application_properties_content }}"
        dest: /BOOT-INF/classes/application.properties
      when: inventory_hostname in ['app']
     
    - name: Удалить standby.signal на pg_slave
      file:
        path: /var/lib/postgresql/data/standby.signal
        state: absent
      when: inventory_hostname in ['pg_slave']
      
    - name: Создать standby.signal на pg_master
      file:
        path: /var/lib/postgresql/data/standby.signal
        state: touch
        owner: postgres
        group: postgres
        mode: '0644'
      when: inventory_hostname in ['pg_master']
      
    - name: Убрать primary_conninfo из pg_slave
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: primary_conninfo
        value: ""
      when: inventory_hostname in ['pg_slave']
      
    - name: Изменить primary_conninfo на pg_master и pg_asyncslave
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: primary_conninfo
        value: "host=pg_slave port=5432 user=replicator password=pass application_name={{ inventory_hostname }}"
      when: inventory_hostname in ['pg_master','pg_asyncslave']
      
    - name: Настраиваем репликацию на pg_slave. synchronous_commit
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: synchronous_commit
        value: "on"
      when: inventory_hostname in ['pg_slave']
 
    - name: Настраиваем репликацию на pg_slave. synchronous_standby_names=FIRST 1
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: synchronous_standby_names
        value: "FIRST 1 (pg_asyncslave, pg_master)"
      when: inventory_hostname in ['pg_slave'] 

    - name: Перезапустить
      docker_container:
        name: "{{ inventory_hostname }}"
        image: "db:local"
        state: started
        restart: true
      run_once: true
      delegate_to: localhost
      when: inventory_hostname in ['pg_master','pg_slave', 'pg_asyncslave']
      
    - name: Убеждаемся что pg_slave стал primary, а pg_asyncslave стал secondary
      community.postgresql.postgresql_query:
        db: "{{ pg_db_name }}"
        login_host: "{{ inventory_hostname }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        query: "select application_name, sync_state from pg_stat_replication;"
      register: replication_status
      until: replication_status.query_result | length > 0
      retries: 30
      delay: 10
      when: inventory_hostname in ['pg_slave']

    - name: Вывести pg_stat_replication
      debug:
        msg:
          - "{{ replication_status.query_result }}"
      when: inventory_hostname in ['pg_slave']
      
    - name: Посчитать количество записей в user_account
      postgresql_query:
        db: "{{ pg_db_name }}"
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        query: "SELECT COUNT(*) FROM user_account;"
      register: count_users_final
      when: inventory_hostname in ['pg_slave', 'pg_asyncslave']

    - name: Вывести количество записей в user_account
      debug:
        msg: "{{ count_users_final.query_result }} записей"
      when: inventory_hostname in ['pg_slave', 'pg_asyncslave']