---
- name: Replication Configuration
  hosts: pg_master
  become: true

  vars:
    pg_admin_user: postgres
    pg_admin_password: postgres
    pg_db_name: user
    pg_hba_conf_path: /var/lib/postgresql/data/pg_hba.conf

  tasks:
    - name: ssl on
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: localhost
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: ssl
        value: 'on'

    - name: wal level replica
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: localhost
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: wal_level
        value: 'replica'

    - name: Set max_wal_senders to 4
      community.postgresql.postgresql_set:
        db: "{{ pg_db_name }}"
        login_host: localhost
        login_user: "{{ pg_admin_user }}"
        login_password: "{{ pg_admin_password }}"
        name: max_wal_senders
        value: 4